### ISSUE TITLE
Fetching the latest pet info...

### ISSUE THREAD

**Issue by jopeydopes** [cferdinandi/fetch#1]
Hey there - 

Just purchased and installed Fetch on my site at www.susieqdogresq.com/test, and it appears to get stuck loading. I carefully installed it according to the Squarespace instruction video three times, was able to see the pets once, and then they disappeared, replaced by the loading text, "Fetching the latest pet info..." and now I am unable to get the pets to load, no matter what I try. I've also made sure that sharing is enabled in my Petfinder settings. Help!

**Comment by cferdinandi** [comment]
Hi there. I'm unable to view your test page. Is it possible that you have visibility restricted to admin or something like that?

**Comment by jopeydopes** [comment]
Ah, I reinstalled it once more and got it working. Not exactly sure what I was doing wrong. 

But one other question, is there any way to prevent on specific pet listing from displaying on the site?

**Comment by cferdinandi** [comment]
Using CSS, yes. BUT, it requires that you're comfortable using Developer Tools in your browser.

If you right click on the pet you'd like to hide and and select `Inspect`, you'll see the markup behind the pet listing. It will probably start you off on the pet's image file. You want to climb up to the `<article>` element. You'll notice an `id` on that element—something like `yui_3_17_2_1_1499709790659_273`.

Each `id` is unique that pet. You can use that to selectively hide a pet, by adding this to your CSS in Squarespace:

```css
#yui_3_17_2_1_1499709790659_273 {
    display: none;
}
```

Of course, replace the string of letters and numbers after the `#` sign with your pet's unique ID.
