### ISSUE TITLE
Images of pets are broken? 

### ISSUE THREAD

**Issue by LanaVitsup** [cferdinandi/fetch#12]
Hi, 
I was thinking about purchasing and using this product to pull in pets from my petfinder page, but I notice that all the pet images in demos and some of the sites i found using this in the issues section are broken. 
Is this a known issue? A temporary glitch? 

Thanks

**Comment by cferdinandi** [comment]
I'm not seeing any missing images, though sometimes the Petfinder API does have a delay when new images are added.
