### ISSUE TITLE
Fetch - broken images

### ISSUE THREAD

**Issue by LanaVitsup** [cferdinandi/fetch#13]
Again, I am sorry to be a stickler but this was working for a while but now I see broken images again on your demo page and some other pages I am looking at posted in the support forum that use your plug in.

I have done a bit of reading, could it be because the sites are https but it pulls in images from http?
Do you have plans to reconcile that? 

![demo out of the box fetch](https://user-images.githubusercontent.com/13949789/40336387-4766ccf2-5d37-11e8-9df2-0ce7d0823b2a.png)

**Comment by cferdinandi** [comment]
I just realized this is a difference in how Chrome and Firefox handle non-encrypted URLs for images on an SSL-enabled site. Chrome shows them anyways. Firefox does not.

Unfortunately, the domain Petfinder provides for the images retrieved via the API is not encrypted and does not offer and SSL-enabled option. As a result, trying to add `https` to the image URLs breaks them altogether.

The main Petfinder website uses SSL-enabled images, but they're served from the AWS CloudFront CDN. There's a pattern I could use to get those from the Pet ID instead, BUT... I don't trust that the URL will be permanent enough to push that into product.

Best bet is to file a feature request with Petfinder's API development team. I'll do so, but would encourage you to as well. The more the better.

**Comment by cferdinandi** [comment]
Just to keep everyone in the loop, here's the exchange I had with Petfinder about this...

```
The images served from the Petfinder API are only available via HTTP, not HTTPS, which results in Mixed Content errors on SSL-enabled pages. This renders OK in webkit browsers, but Firefox doesn't render those images.

I noticed the same photos on Petfinder.com are served from an AWS Cloudfront CDN. Any chance you can do the same via the API, or least install an SSL cert on that domain?

---

We're looking into updating the API to be a lot more functional in the near future, but as it is right now, you will indeed encounter some mixed content errors in certain browsers due to API only showing http versions of photos.  I don't have an ETA on when the API will be improved, but it is on our radar.

---

I hear you on improving the API, but... is there any reason you can, as an interim fix, add an SSL certificate to the domain that serves these images? 

These days, you can even get one for free from Let's Encrypt. It's a 0 cost thing that would go a long way to making the experience better.

---

This likely won't be happening immediately, but I've sent this on for review by our system administrators.
```

Long story short: not a priority for them and they've made 0 commitment to fixing or improving things. 

And before you get optimistic about API improvements mentioned in the thread, they've been talking about doing that for... 5, maybe 6 years. Still nothing.

**Comment by wellrush** [comment]
@cferdinandi I'm able to see images on your demo but they are all broken on my page. How can this be solved? (I'm on Chrome)

**Comment by wellrush** [comment]
@cferdinandi www.operationfreedomride.com/petfinder

**Comment by wellrush** [comment]
https://operationfreedomride.com/petfinder/

Wordpress built with Elementor


Ben Cometa | 585.314.8877 | Well Rush

ᐧ

**Comment by cferdinandi** [comment]
@wellrush the links you provided 404. No IP address found for that URL.

**Comment by wellrush** [comment]
Appears to be working here still or again now


Ben Cometa | 585.314.8877 | Well Rush
ᐧ

**Comment by cferdinandi** [comment]
<img width="1392" alt="screen shot 2019-01-25 at 5 46 38 pm" src="https://user-images.githubusercontent.com/1724852/51776982-31f27780-20c9-11e9-8621-f5edfe717c37.png">

Not for me :(

**Comment by wellrush** [comment]
Thanks, reached out to host. I think this is a browser issue - site is
showing that it's up


Ben Cometa | 585.314.8877 | Well Rush

ᐧ
ᐧ

**Comment by cferdinandi** [comment]
@wellrush The site is working now for me.

So, here's what's happening. Petfinder sends images *only* in http format (no SSL). You seem to have your server configured to redirect *all* assets---even ones that are not hosted on your server---from http to https. 

Petfinder doesn't host those images with https, so they all 404 and fail to load.
