### ISSUE TITLE
HTTPS Error 

### ISSUE THREAD

**Issue by BruceFranz** [cferdinandi/fetch#14]
The website that the code is running on is secured. Whenever I use this code I recive an error that this site is not fully protected. When inspecting element this is the message that comes up. 
"Resources - mixed content
This page includes HTTP resources.
Reload the page to record requests for HTTP resources."

Is there anyway to fix this?

**Comment by cferdinandi** [comment]
It's related to this: https://github.com/cferdinandi/fetch/issues/13

And unfortunately, it's entirely in Petfinder's control at this point.
