### ISSUE TITLE
Petfinder FETCH for 2nd location on same website?

### ISSUE THREAD

**Issue by operationadopt** [cferdinandi/fetch#15]
Chris,
The nonprofit is expanding into a second geographical area.  Our ideal goal is to have separate adoption pages on square space for the different areas.  We just found out in petfinder that we can create a second location.  So right now the workaround is to name the animals and then put the state they are in - in parenthesis after their names.  What we want to do is have the animals in one state only on their separate pages.

**Comment by cferdinandi** [comment]
Thinking about this more... do/will the different locations each have their own Petfinder Shelter ID, or is the desire to keep them all together?

**Comment by operationadopt** [comment]
I desire them to be separate accounts so each location’s animals are on their own page of the website.

**Comment by cferdinandi** [comment]
This is a touch complicated, but this can absolutely be done. 

**The approach:** initialize Fetch with a different shelter ID depending on which page you're on.

To make it work, you'll want to update the HTML for your fetch container by adding `data-petfinder="YOUR SHELTER ID"`, with the shelter ID for that listing as it's value.

```html
<div class="fetch-container" data-petfinder="AB123">
    Anything you want to display if Fetch isn't supported by the visitor's browser.
</div>
```

Where you initialize Fetch in your JavaScript, you'll want to look for elements with that `data-petfinder` attribute, grab it's value. Then, you'll pass that value into Fetch.

```js
var shelterID = document.querySelector('[data-petfinder]');
if (shelterID) {
	fetch.init({
		key: "YOUR API KEY",
		shelter: shelterID.getAttribute('data-petfinder'),
		count: 25,
	});
}
```

Hope that helps, and let me know if you have any questions!

**Comment by operationadopt** [comment]
Thank you Chris!  When I get the second shelter ID I’ll try it!
