### ISSUE TITLE
Adoption Forms Link CSS

### ISSUE THREAD

**Issue by snyders08** [cferdinandi/fetch#16]
I'm having issues adding the CSS to make the adoption form link to look like the one displayed here: https://fetch.gomakethings.com/adoption-forms/?petID=41666386

**Comment by cferdinandi** [comment]
Can you tell me what you've tried and what's not working? A link to a demo site would be helpful, too.

**Comment by snyders08** [comment]
Link: http://www.babinskifoundation.org/adoptable-animals?petID=42043235

I use Squarespace, for some reason with this template the links are the same as body text.

Thank You,
Donald Snyders
Babinski Properties & Babinski Foundation
(218) 537-0906

________________________________

**Comment by cferdinandi** [comment]
Ah, you would need to add a class to the link so that you can style it using the `adoptionFormClass` option: https://fetch.gomakethings.com/documentation/#options-with-fetch-init

Looking at the other buttons on your site, you'd want to do this to make that look like your other buttons.

```js
fetch.init({
	// API Defaults
	key: null, // Your Petfinder API key
	shelter: null, // Your shelter ID

	// Template info
	adoptionFormClass: 'sqs-system-button sqs-editable-button-layout sqs-editable-button-style',
});
```
