### ISSUE TITLE
Change image size

### ISSUE THREAD

**Issue by lindahl2014** [cferdinandi/fetch#18]
Hi - Could you let me know of any css code that would allow me to change the default photo size? Would like the image to be much larger on the detail page, and slightly larger on the list page. Thanks!

**Comment by cferdinandi** [comment]
Every element in Fetch has a custom class prefixed with `.fetch-*` that you can hook into to nudge-and-tweak the styling.

This is for advanced users only. Please use your browser's Developer Tools to explore the available classes and styling hooks and test changes. I unfortunately am unable to document every class in detail.

*__Note:__ I cannot provide support for custom style changes outside of [customized layout engagements](https://fetch.gomakethings.com/pricing/#customized-layouts).*

**Comment by lindahl2014** [comment]
Got it - thanks for the reply!
Rebecca

---
cell (415) 601-8908
