### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Arydiel** [cferdinandi/fetch#2]
We created the API token but its not working. Is there a step missing? Using Wordpress. (Sorry we may just have shelter ID wrong but its not intuitive where to find it)
It's showing this: 
Unable to get data from Petfinder. Using expired localStorage data instead.  fetch.js:2:22902
Unable to retrieve Petfinder data from the API or localStorage.
Dev is here.
https://weathervanegraphics.com/client/humane/wp/sample-page/

**Comment by Arydiel** [comment]
Never mind. Client shelter ID need CAPITAL letters (ugh. Well maybe someone else will be helped by this.)

**Comment by techpurple** [comment]
Thank you...helped me...
