### ISSUE TITLE
Adoption Application button is not displaying

### ISSUE THREAD

**Issue by gwenski** [cferdinandi/fetch#21]
I am using the Fetch Wordpress plugin. Everything is working great except that I can't see the Adoption Application button. 
**live site URL:** 
https://www.coloradocaninerescue.org/petfinder-test/

**WP code**:
[fetch key="026a3db4bbdbbec89ae1dab99c8f067a" shelter="CO325" allpetstitle="Available Dogs" showfilters="false" adoptionFormLink: "https://www.coloradocaninerescue.org/adopt-a-dog-2/adoption-application/" adoptionFormText: "Fill out an Adoption Application" adoptionformclass="appbutton"]
<a href="https://www.petfinder.com/search/pets-for-adoption/?shelter_id%5B0%5D=CO325&amp;sort%5B0%5D=recently_added"></a>
[/fetch]

**appbutton class css:**
.appbutton {
	background-color: coral;
	color: #ffffff;
  border: none;
	border-radius: 4px;
  padding: 20px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 4px 2px;
}
Thanks for your help!

**Comment by cferdinandi** [comment]
You're using colons where you should have equal signs.

This:

```
adoptionFormLink: "https://www.coloradocaninerescue.org/adopt-a-dog-2/adoption-application/"
```

Should be this:

```
adoptionFormLink="https://www.coloradocaninerescue.org/adopt-a-dog-2/adoption-application/"
```

Same goes for the `adoptionFormText` attribute.
