### ISSUE TITLE
Browsers 

### ISSUE THREAD

**Issue by jblack0815** [cferdinandi/fetch#4]
Your Fetch documentation provides a work-around if an individual's browser will not work with Fetch.  My question is, are there any identified browers that do not work with Fetch?

Thank you,

Jan Black

**Comment by cferdinandi** [comment]
[From the homepage](https://fetch.gomakethings.com/#browser-compatibility):

> Fetch works in all modern browsers, and IE 9 and above. Older and unsupported browsers will be shown a link to your pets on Petfinder.com.
